### ISSUE TITLE
How do I use the trained models in hcaptcha-challenger?

### ISSUE THREAD

**Issue by Jarvn** [captcha-challenger/hcaptcha-model-factory#48]
How do I use the trained models in hcaptcha-challenger?

I tried to change the .onnx model to trained one but idk if that's the right way to do it?

**Comment by QIN2DIM** [comment]
hcaptcha-challenger's lifecycle mechanism ensures that the local model version is always the same as the upstream version, so you cannot replace the model file with the same name.

When encountering the `sunflower` target, use the `sunflower.onnx` model. If your model name is also 'sunflower.onnx', then it will be overwritten

```yaml
sunflower:
  zh: [ "向日葵" ]
  en: [ "sunflower" ]
```

So you should adjust `objects.yaml` to change this field, like `sunflower-myself: `. However, the "cycle mechanism" also maintains the version of the `Objects.yaml` file, that is, covering the local configuration file, so we need to go deep into the source code to discuss, because I did not consider the situation of the user's own training model before.

**Comment by Jarvn** [comment]
So I just need to replace original .onnx model file with a trained .onnx file with a different name? and also change objects.yaml to the trained model file name?

Sorry, i'm a bit confused

**Comment by beiyuouo** [comment]
Yes, you are right.
